/**
 * The eighteen moments, as data. The source is plan/redesign/v3/ADVISOR-craft.md §6 —
 * one row per moment, copied rather than summarised, because this page is the inventory
 * M11 mirrors into Figma and the catalog's numbers are the spec.
 *
 * `code` names the file that implements the real thing. Where the demo on this page is
 * a miniature rather than that component (an overlay that cannot open inside a box, a
 * sequence that needs the whole store), `real` says so instead of implying otherwise.
 */
export interface Moment {
  id: number;
  name: string;
  /** What the person did, or what the app noticed. */
  trigger: string;
  moves: string;
  ms: string;
  easing: string;
  stagger: string;
  reduced: string;
  avoid: string;
  code: string;
  /** "real" = built from the shipped component; "miniature" = same tokens, small stage. */
  real: "real" | "miniature";
  /** Labels for the Play control. More than one means the moment has variants. */
  plays?: string[];
  signature?: boolean;
}

export const moments: Moment[] = [
  {
    id: 1,
    name: "Row hover",
    trigger: "Pointer enters a row",
    moves: "Row background steps from surface-1 to surface-2. The action cluster fades in and slides 6px.",
    ms: "90 background · 140 cluster",
    easing: "ease-out",
    stagger: "None",
    reduced: "Background only. No slide.",
    avoid: "Layout shift. The cluster's track is always reserved.",
    code: "components/relay/queue-row.tsx",
    real: "miniature",
  },
  {
    id: 2,
    name: "Row focus",
    trigger: "Keyboard focus lands on a row",
    moves: "A 2px ring at 2px offset, drawn with box-shadow, plus the hover background.",
    ms: "0 — instant",
    easing: "None",
    stagger: "None",
    reduced: "Identical.",
    avoid: "Animating the ring in. It must be there on the frame the key lands.",
    code: "components/ui/sizing.ts (FOCUS)",
    real: "miniature",
  },
  {
    id: 3,
    name: "Press",
    trigger: "Pointer goes down on a button",
    moves: "The button scales to 0.985. Only buttons scale, never a row.",
    ms: "80 down · 120 up",
    easing: "ease-out",
    stagger: "None",
    reduced: "None.",
    avoid: "Scaling a 64px row instead of the button.",
    code: "components/ui/button.tsx",
    real: "miniature",
  },
  {
    id: 4,
    name: "Mark done",
    trigger: "Click, Enter or ⌘↵ on the primary action",
    moves:
      "The check draws over the card that is leaving. The hero leaves. The next row lifts out of the list and becomes the hero, and the check lifts away as it arrives. The gap closes. The counter rolls. The toast arrives.",
    ms: "≈420 end to end, measured frame by frame",
    easing: "ease-out, spring-layout",
    stagger: "24ms per row, capped at 5",
    reduced: "The check, the promotion and the roll become instant. The toast fades in over 120ms.",
    avoid:
      "Letting the check outlive the card it confirms. Until v4 the promoted card arrived at 140ms and the check drew until 290, so for a tenth of a second the tick sat over the item that replaced the one just finished.",
    code: "components/relay/hero.tsx · queue.tsx · check-draw.tsx",
    real: "miniature",
    signature: true,
  },
  {
    id: 5,
    name: "Undo",
    trigger: "Undo in the toast, or ⌘Z",
    moves: "The item flies from the toast back to its rank. The hero restores with a crossfade.",
    ms: "≈420",
    easing: "spring-layout",
    stagger: "None",
    reduced: "Instant.",
    avoid: "Playing Mark done backwards. It reads as a glitch. Undo is one move, not a rewind.",
    code: "components/relay/undo-toast.tsx · hero.tsx",
    real: "miniature",
  },
  {
    id: 6,
    name: "Undo toast",
    trigger: "After Mark done",
    moves: "Enters from the bottom-left, 8px up and fading in. 56px tall, 360px wide. Holds 8s, then leaves.",
    ms: "220 in · 160 out",
    easing: "ease-out in, ease-in out",
    stagger: "None",
    reduced: "Fade only. Holds 12s.",
    avoid: "Landing over the top bar's search field, or a sub-44px Undo target.",
    code: "components/ui/toast.tsx · components/relay/toast-bridge.tsx",
    real: "real",
  },
  {
    id: 7,
    name: "Countdown",
    trigger: "Each simulated minute",
    moves: "The digits roll. The arc advances one step. At 15 minutes left the arc shifts to the Act-now hue, once.",
    ms: "320 roll · 600 hue",
    easing: "ease-in-out",
    stagger: "None",
    reduced: "Digits swap. The arc steps each minute. No hue transition.",
    avoid: "Pulsing. Nothing on this screen may pulse.",
    code: "components/relay/countdown-arc.tsx",
    real: "miniature",
  },
  {
    id: 8,
    name: "Tier re-sort",
    trigger: "A score changes",
    moves: "Rows whose index changed reposition. The moved row gets a tint that fades to nothing so the eye can find it.",
    ms: "spring-layout · 900 wash",
    easing: "spring-layout",
    stagger: "24ms",
    reduced: "Positions jump. The wash stays, because it is colour and not motion.",
    avoid: "Animating every row when one moved.",
    code: "components/relay/queue.tsx · app/globals.css (.tint-wash)",
    real: "miniature",
  },
  {
    id: 9,
    name: "New urgent item",
    trigger: "A higher-ranked item arrives",
    moves: "A 48px band slides down inside the hero. The band's border runs one light sweep, left to right.",
    ms: "260 slide · 700 sweep, once",
    easing: "ease-out",
    stagger: "None",
    reduced: "The band fades in. No sweep.",
    avoid: "Repeating the sweep. Once per arrival, ever.",
    code: "components/relay/new-urgent-band.tsx",
    real: "real",
  },
  {
    id: 10,
    name: "Why is this first?",
    trigger: "Click the link",
    moves: "The panel scales from 0.96 out of the link's own corner. The four weight bars fill left to right.",
    ms: "180 panel · 240 bars",
    easing: "ease-out",
    stagger: "50ms per bar",
    reduced: "Bars render filled. The panel fades over 120ms.",
    avoid: "Bars that animate on every re-open. Animate on the first open per item only.",
    code: "components/relay/why-popover.tsx · why-factors.tsx",
    real: "miniature",
  },
  {
    id: 11,
    name: "Right sheet",
    trigger: "Row click, or Enter",
    moves: "The panel slides 24px in from the right and fades in. Its sections follow one after another.",
    ms: "spring-sheet ≈520",
    easing: "spring-sheet",
    stagger: "28ms per section, 4 max",
    reduced: "A 140ms fade.",
    avoid: "A sheet that covers the row that opened it. The scrim dims, and the source row stays visible at 1440.",
    code: "components/relay/item-detail-sheet.tsx",
    real: "miniature",
  },
  {
    id: 12,
    name: "Bottom sheet",
    trigger: "Tap, at 390",
    moves: "The sheet rises and snaps at 55% or 94% of the screen.",
    ms: "spring-sheet",
    easing: "spring-sheet",
    stagger: "None",
    reduced: "A fade.",
    avoid: "Rubber-banding past 94%.",
    code: "components/relay/item-detail-sheet.tsx (Vaul)",
    real: "miniature",
  },
  {
    id: 13,
    name: "Command palette",
    trigger: "⌘K",
    moves:
      "The scrim fades in and blurs. The panel scales from 0.97. The selection highlight glides between rows.",
    ms: "160 scrim · 200 panel · 120 highlight",
    easing: "ease-in-out",
    stagger: "None",
    reduced: "No blur. The highlight jumps.",
    avoid: "Blurring the whole app. Blur the scrim layer only, never the page.",
    code: "components/relay/command-palette.tsx",
    real: "miniature",
  },
  {
    id: 14,
    name: "Theme switch",
    trigger: "The mode toggle",
    moves: "A circular reveal grows from the toggle's centre until it covers the page.",
    ms: "420",
    easing: "ease-in-out",
    stagger: "None",
    reduced: "Instant swap. No transition.",
    avoid: "Running the reveal on first paint.",
    code: "lib/theme-transition.ts",
    real: "miniature",
  },
  {
    id: 15,
    name: "Tabs",
    trigger: "Click a tab",
    moves: "The active pill glides to the new tab. The label does not move.",
    ms: "200",
    easing: "ease-in-out",
    stagger: "None",
    reduced: "The pill jumps.",
    avoid: "Animating the label text along with the pill.",
    code: "components/relay/update-tabs.tsx",
    real: "real",
  },
  {
    id: 16,
    name: "Skeleton to content",
    trigger: "Data is ready",
    moves: "The blocks crossfade to the content. No shimmer.",
    ms: "180",
    easing: "ease-out",
    stagger: "30ms per row, 6 max",
    reduced: "Instant.",
    avoid: "A shimmer loop. The data resolves in under 50ms, and a shimmer lies about latency.",
    code: "components/ui/skeleton.tsx",
    real: "real",
  },
  {
    id: 17,
    name: "All clear",
    trigger: "The queue empties",
    moves: "The aurora fades in. The headline rises 12px behind it. Today's list steps up one line at a time.",
    ms: "900 aurora · 420 headline",
    easing: "ease-out",
    stagger: "40ms per item, 8 max",
    reduced: "The aurora is static. The headline fades over 160ms.",
    avoid: "Confetti. Never confetti in a workplace tool.",
    code: "components/relay/all-clear.tsx",
    real: "miniature",
  },
  {
    id: 18,
    name: "Count change",
    trigger: "A tile or tier count changes",
    moves: "The number rolls. On an increase only, the band's hairline flashes to line-2 and back.",
    ms: "320 roll · 500 flash",
    easing: "ease-out",
    stagger: "None",
    reduced: "The number swaps. The flash stays.",
    avoid: "Flashing on a decrease. A decreasing count is good news.",
    code: "components/relay/risk-tile.tsx · queue.tsx",
    real: "miniature",
    plays: ["Count up", "Count down"],
  },
];
