export const copy = {
  appName: "Relay",
  nav: { work: "My work", team: "Team", updates: "Updates", lookup: "Look up" },
  search: "Search orders, people, tickets",
  greeting: { morning: "Good morning, {name}.", afternoon: "Good afternoon, {name}." },
  // D2: three modes, all first class — not a settings toggle. "Wire" is the brief's
  // low-fidelity deliverable, reachable live from the top bar.
  modeSwitch: { label: "Appearance", light: "Light", dark: "Dark", wire: "Wire" },
  status: {
    needYou: "{n} things need you now.",
    needYouOne: "1 thing needs you now.",
    nothingUrgent: "Nothing urgent. {n} left before your shift ends.",
    progress: "{done} of {total} done today.",
    truckLine: "{carrier} leaves in {rel}",
    // v3 M4 (§5.1): the status line is three clauses joined by "·", so each one drops
    // its full stop. The first is the operative clause and is the only part set in
    // --text-1 600 — "2 need you now · UPS Ground in 50 min · 4 of 10 done".
    clauseNeedYou: "{n} need you now",
    clauseNeedYouOne: "1 needs you now",
    clauseNothingUrgent: "Nothing urgent",
    clauseTruck: "{carrier} in {rel}",
    clauseTruckAt: "{carrier} at {hhmm}",
    clauseTruckGone: "{carrier} has left",
    clauseProgress: "{done} of {total} done",
    clauseLeft: "{n} left before your shift ends",
  },
  hero: {
    now: "Do this now",
    next: "Do this next",
    later: "Up next when you are ready",
    of: "{i} of {n}",
    whyFirst: "Why first:",
    nextStep: "Next step: {action}",
    working: "Working on it · {n} min",
    ordersWaiting: "{n} orders waiting",
    truckAt: "{carrier} truck {hhmm}",
  },
  actions: {
    start: "Start",
    done: "Mark done",
    help: "Ask for help",
    more: "More",
    waiting: "Waiting on someone",
    notMine: "Not mine",
    handOff: "Hand off to a teammate",
    later: "Move to later",
    reassign: "Reassign",
    assign: "Assign",
    seeWork: "See work",
    showMore: "Show {n} more",
    showLess: "Show less",
    undo: "Undo",
    gotIt: "Got it",
    showMe: "Show me",
    stay: "Stay here",
    acknowledge: "Acknowledge",
  },
  tiers: {
    now: { label: "Act now", helper: "A truck, a person, or many orders are at risk." },
    next: { label: "Up next", helper: "Matters today. A clock is running." },
    later: { label: "When you can", helper: "Real work. Nobody is blocked yet." },
    fyi: { label: "For your info", helper: "No action needed." },
    done: { label: "Done today", withCount: "Done today ({n})" },
    empty: "Nothing here.",
    waitingGroup: "Waiting on others ({n})",
    laterGroup: "Moved to later ({n})",
  },
  time: {
    dueIn: "Due in {n} min",
    due: "Due {hhmm}",
    lateMin: "Late by {n} min",
    lateHr: "Late by {n} h",
    tomorrow: "Tomorrow {hhmm}",
    ago: "{rel} ago",
    justNow: "Just now",
  },
  why: {
    title: "Why is this first?",
    showScore: "Show the score",
    howLink: "How we sort your work",
    scoreLine: "Time {t} + Orders {b} + Impact {i} = {score}",
    // §5.2: the bar itself is decorative (a 1.62:1 fill is not a real contrast pair);
    // this is the text alternative a screen reader gets instead, and the number a
    // sighted reader gets too — "value of max", not just the raw value.
    factorValue: "{value} of {max}",
    factors: {
      lateBy: "It is late by {rel}.",
      dueIn: "It is due at {hhmm}, in {rel}.",
      blocked: "{n} orders are waiting on it.",
      noneBlocked: "Nothing is waiting on it.",
      noDue: "It has no deadline.",
      truck: "It must be ready for the {carrier} truck at {hhmm}.",
      customerHigh: "Customers will feel it.",
      customerLow: "A customer may notice.",
      compliance: "It is required by law or policy.",
      escalated: "Someone escalated it.",
      safety: "Someone could get hurt. Safety always comes first.",
      noImpact: "No extra impact factors.",
    },
    verdict: {
      safety: "Safety always makes it Act now, above the score.",
      now: "{score}, 60 or higher, means Act now.",
      next: "{score}, 30 to 59, means Up next.",
      later: "{score}, under 30, means When you can.",
    },
    compareAbove: "Ranks above {title} because it scores higher ({scoreA} to {scoreB}).",
    topOfQueue: "The next item is at the bottom of the queue.",
  },
  toast: {
    done: "Done. {done} of {total} done today.",
    restored: "Restored.",
    paused: "Paused {title}.",
    moved: "Moved to {name}.",
    sentBack: "Sent back to the team.",
    helpSent: "Sent to Danielle. She will check in.",
    waiting: "Waiting on {who}. Back at {hhmm}.",
    notInPrototype: "This is not part of the prototype.",
  },
  help: {
    title: "What's stopping you?",
    options: ["I need information", "Something is broken", "I need another person", "Other"],
    note: "Add a note (optional)",
    send: "Send to Danielle",
    chip: "Help asked",
  },
  laterDisabled: "Do now items cannot be moved. Ask for help instead.",
  allClear: {
    title: "You're all caught up.",
    body: "Nothing needs you right now. New work will show up here, already sorted.",
    meta: "{n} done today.",
    hint: "New items will appear here",
    team: "Help your team",
    updates: "See updates",
  },
  newUrgent: "New and more urgent: {title}.",
  changedPlace: "1 item changed place.",
  showIt: "Show it",
  live: {
    doneNext: "Done. Next: {title}.",
    doneCaughtUp: "Done. All caught up.",
    newUrgentItem: "New urgent item: {title}.",
  },
  team: {
    status: "Day shift · Outbound · {on} working, {brk} on break, {out} out today.",
    live: "Live · updated {hhmm}",
    statusNeedYou: "{n} things need you. Everyone else is on track.",
    statusNeedYouOne: "1 thing needs you. Everyone else is on track.",
    statusAllTrack: "Everyone is on track.",
    tiles: { now: "Act now across team", help: "May need help", noOwner: "No owner", truck: "Next truck" },
    tileSubs: {
      now: "{n} due by {hhmm}",
      help: "{title}, no update {n} min",
      noOwner: "{name} is out today",
      noOwnerNone: "Everyone is on shift",
      truck: "{n} orders at risk · in {rel}",
      truckOnTrack: "On track",
    },
    board: "Team board",
    // §7.4: three caps heads over the roster's tabular columns — v2 printed "2 · 3 · 1"
    // with no key for what any of the three numbers meant.
    columns: { now: "Now", next: "Next", later: "Later" },
    needsYou: "Needs you",
    needsYouEmpty: "Nothing needs you right now.",
    needsYouNoOwner: "{title}. No owner. Due {hhmm}.",
    needsYouNoOwnerNoDue: "{title}. No owner.",
    needsYouHelp: "{title}. No update for {n} min.",
    needsYouAsked: "{name} asked for help on {title}.",
    needsYouSafety: "{title}. Safety always comes first.",
    // §7.4: the verb is specific, never the generic "Check in" — this opens that
    // person's queue, read only, scrolled to the item that flagged them (Needs you),
    // or to the top of it (selecting a roster row).
    openQueue: "Open {name}'s queue",
    // The roster's one visible control (the ghost row menu): reassigns the person's
    // current item, the one real "quick action" a manager needs without opening the
    // full sheet.
    reassignCurrent: "Reassign {name}'s current item",
    // §4.2 / README P0 8, P1 9: never a per person elapsed time (the surveillance
    // pattern the deck rejects) — time appears only on the item, only when it signals
    // a problem, via the item's own time pill.
    rightNow: { on: "On: {title}", available: "Available", onBreak: "On break", out: "Out today" },
    mayNeedHelp: "May need help",
    load: { light: "Light", busy: "Busy", full: "Full" },
    loadCounts: "{now} · {next} · {later}",
    mirror: "Everyone on the team sees this same board.",
    personNote: "This is what {name} sees.",
    reassignTitle: "Who should do this?",
    findTeammate: "Find a teammate",
    suggested: "Suggested",
    clearFilter: "Clear filter",
    checkInTitle: "{name}'s queue",
    checkInEmpty: "Nothing in the queue.",
  },
  trucks: { title: "Next trucks", atRisk: "{n} orders at risk", onTrack: "On track", none: "No trucks left today" },
  truckClock: {
    leavesIn: "{carrier} leaves {door} in {rel}",
    leavesAt: "{carrier} leaves {door} at {hhmm}",
    departed: "{carrier} left {door}",
    // The rail card carries the carrier as its title and the door as a chip, so the
    // line under them says the one thing neither of those does: when it goes. The three
    // keys above keep the full sentence for the detail panel, which has no such title.
    railLeavesIn: "Leaves in {rel}",
    railLeavesAt: "Leaves at {hhmm}",
    railDeparted: "Already left",
    atRisk: "{n} orders at risk",
    allOnTrack: "All orders on track",
    none: "No trucks left today",
  },
  shiftTimeline: {
    label: "Shift timeline",
    now: "Now",
    handoff: "Handoff {hhmm}",
  },
  myShift: { title: "My shift", doneOf: "{done} of {total} done", ends: "Shift ends {hhmm}" },
  updates: {
    title: "Updates",
    tabs: { forYou: "For you", team: "Team", system: "System" },
    markRead: "Mark as read",
    empty: "No updates. When something changes, it will show up here.",
    emptyTab: "Nothing here.",
    selectHint: "Select an update to read it here.",
    seeAll: "See all updates",
    from: "From {name}",
    fromSystem: "System",
  },
  lookup: { empty: "Type an order number, a name, or a word like printer." },
  shortcuts: "J K move · Enter open · E mark done · Z undo · ? all shortcuts",
  demo: {
    pill: "Prototype controls",
    viewingAs: "Viewing as",
    priya: "Priya (coordinator)",
    danielle: "Danielle (manager)",
    clock: "Now {hhmm}",
    jump: "Jump 15 min",
    reset: "Reset to 10:40",
    inject: "Send a new urgent item",
    resetAll: "Reset demo",
    clockLabel: "Clock",
    label: "Demo",
  },
  drawer: {
    assignedTo: "Assigned to",
    ordersWaiting: "Orders waiting",
    unitsAffected: "Units affected",
    truck: "Truck",
    created: "Created",
    itemId: "Item ID",
    source: "Source",
    status: "Status",
    due: "Due",
    noOwner: "No owner",
    // §6.2: never a raw source name ("Created 10:05 by Order") — a natural sentence
    // built from sourcePhrases below ("Opened 10:05 from an order issue").
    activityCreated: "Opened {hhmm} from {source}",
    activityStarted: "Started by {name} at {hhmm}",
    message: "Message {name}",
    messagingToast: "Messaging is not part of this prototype.",
  },
  statusLabels: {
    open: "Open",
    in_progress: "In progress",
    waiting: "Waiting",
    snoozed: "Moved to later",
    done: "Done",
  },
  itemDetail: {
    activity: "Activity",
    prev: "Previous item",
    next: "Next item",
    close: "Close",
    notFound: "This item isn't in the queue anymore.",
    backToWork: "Back to My work",
    sourceHistory: "Source & history",
    people: "People",
    unassigned: "Unassigned",
  },
  howModal: {
    title: "How we sort your work",
    body: "We look at four things. How soon it is due. How many orders are waiting on it. Whether customers will feel it. Whether it is about safety or the law.",
    now: "means a truck, a person, or many orders are at risk. Safety always goes here.",
    next: "matters today, and a clock is running.",
    later: "is real work, but nobody is blocked yet.",
    footer: "Inside each group, the most important thing is on top. You can always ask for help or hand something off.",
  },
  waitingPopover: {
    who: "Who are you waiting on?",
    suggestions: ["Carrier", "Maintenance", "Customer service", "Vendor"],
    checkBack: "Check back at",
    in30: "In 30 min",
    in1h: "In 1 hour",
    atCutoff: "At {hhmm}",
  },
  notMineReasons: ["Wrong area", "I don't have access", "Duplicate", "Other"],
  moveLaterOptions: { in1h: "In 1 hour", afterLunch: "After lunch (12:30)", pick: "Pick a time" },
  settings: { label: "Settings", tooltip: "Not part of this prototype" },
  sourceLabels: {
    order: "Order",
    system: "System",
    comms: "Message",
    carrier: "Carrier",
    customer: "Customer",
    inventory: "Inventory",
    safety: "Safety",
    compliance: "Compliance",
    floor: "Floor",
    fyi: "Info",
  },
  // §6.2: the natural-language half of an activity line ("Opened 10:05 from {this}").
  sourcePhrases: {
    order: "an order issue",
    system: "a system alert",
    comms: "a message",
    carrier: "a carrier update",
    customer: "a customer report",
    inventory: "an inventory check",
    safety: "a safety report",
    compliance: "a compliance check",
    floor: "the floor",
    fyi: "an update",
  },
  palette: {
    title: "Command palette",
    recent: "Recent",
    actions: "Actions",
    people: "People",
    items: "Items",
    empty: "No results.",
    footer: "↑↓ Navigate · ↵ Select · Esc Close",
    actionMarkDone: "Mark done",
    actionAskHelp: "Ask for help",
    actionSwitchTo: "Switch to {name}",
    actionSendUrgent: "Send a new urgent item",
    actionWireframeOn: "Turn on wireframe mode",
    actionWireframeOff: "Turn off wireframe mode",
    actionThemeDark: "Switch to dark mode",
    actionThemeLight: "Switch to light mode",
    actionShortcuts: "Keyboard shortcuts",
  },
  shortcutsSheet: {
    title: "Keyboard shortcuts",
    rows: [
      { keys: "J / K", label: "Move the selection" },
      { keys: "Enter", label: "Open the selected row" },
      { keys: "E", label: "Mark the hero done" },
      { keys: "H", label: "Ask for help" },
      { keys: "⌘Z", label: "Undo" },
      { keys: "⌘K", label: "Open the command palette" },
      { keys: "Esc", label: "Close a sheet or the palette" },
      { keys: "?", label: "Show this list" },
    ],
  },
  handheld: { needYou: "{n} need you" },
  chips: { workingOnIt: "Working on it" },
  shift: { line: "{name} · {h}h {m}m left", ended: "{name} · Shift ended" },
};

export function t(str: string, vars: Record<string, string | number> = {}): string {
  return str.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? `{${key}}`));
}
