export const copy = {
  appName: 'Relay',
  nav: { work: 'My work', team: 'Team', updates: 'Updates', lookup: 'Look up' },
  search: 'Search orders, people, tickets',
  greeting: { morning: 'Good morning, {name}.', afternoon: 'Good afternoon, {name}.' },
  status: {
    needYou: '{n} things need you now.', needYouOne: '1 thing needs you now.',
    nothingUrgent: 'Nothing urgent. {n} left before your shift ends.',
    progress: '{done} of {total} done today.',
  },
  hero: { now: 'Do this now', next: 'Do this next', later: 'Up next when you are ready',
          of: '{i} of {n}', whyFirst: 'Why first:', nextStep: 'Next step: {action}',
          working: 'Working on it · {n} min', ordersWaiting: '{n} orders waiting', truckAt: '{carrier} truck {hhmm}' },
  actions: { start: 'Start', done: 'Mark done', help: 'Ask for help', more: 'More',
             waiting: 'Waiting on someone', notMine: 'Not mine', handOff: 'Hand off to a teammate',
             later: 'Move to later', reassign: 'Reassign', assign: 'Assign', seeWork: 'See work',
             checkIn: 'Check in', showMore: 'Show {n} more', showLess: 'Show less', undo: 'Undo',
             gotIt: 'Got it', showMe: 'Show me', stay: 'Stay here' },
  tiers: {
    now:   { label: 'Do now',       helper: 'A truck, a person, or many orders are at risk.' },
    next:  { label: 'Up next',      helper: 'Matters today. A clock is running.' },
    later: { label: 'Later today',  helper: 'Real work. Nobody is blocked yet.' },
    fyi:   { label: 'For your info',helper: 'No action needed.' },
    done:  { label: 'Done today', withCount: 'Done today ({n})' },
    empty: 'Nothing here.',
    waitingGroup: 'Waiting on others ({n})', laterGroup: 'Moved to later ({n})',
  },
  time: { dueIn: 'Due in {n} min', due: 'Due {hhmm}', lateMin: 'Late by {n} min', lateHr: 'Late by {n} h',
          tomorrow: 'Tomorrow {hhmm}', ago: '{rel} ago', justNow: 'Just now' },
  why: { title: 'Why this is ranked here', showScore: 'Show the score', howLink: 'How we sort your work',
         scoreLine: 'Time {t} + Orders {b} + Impact {i} = {score}',
         factors: {
           lateBy: 'It is late by {rel}.', dueIn: 'It is due at {hhmm}, in {rel}.',
           blocked: '{n} orders are waiting on it.', truck: 'It must be ready for the {carrier} truck at {hhmm}.',
           customerHigh: 'Customers will feel it.', customerLow: 'A customer may notice.',
           compliance: 'It is required by law or policy.', escalated: 'Someone escalated it.',
           safety: 'Someone could get hurt. Safety always comes first.',
         } },
  toast: { done: 'Done. {done} of {total} done today.', restored: 'Restored.', paused: 'Paused {title}.',
           moved: 'Moved to {name}.', sentBack: 'Sent back to the team.', helpSent: 'Sent to Danielle. She will check in.',
           waiting: 'Waiting on {who}. Back at {hhmm}.', notInPrototype: 'This is not part of the prototype.' },
  help: { title: "What's stopping you?", options: ['I need information','Something is broken','I need another person','Other'],
          note: 'Add a note (optional)', send: 'Send to Danielle', chip: 'Help asked' },
  laterDisabled: 'Do now items cannot be moved. Ask for help instead.',
  allClear: { title: "You're all caught up.", body: 'Nothing needs you right now. New work will show up here, already sorted.',
              meta: '{n} done today.', team: 'Help your team', updates: 'See updates' },
  newUrgent: 'New and more urgent: {title}.',
  changedPlace: '1 item changed place.', showIt: 'Show it',
  live: { doneNext: 'Done. Next: {title}.', doneCaughtUp: 'Done. All caught up.', newUrgentItem: 'New urgent item: {title}.' },
  team: {
    status: 'Day shift · Outbound · {on} working, {brk} on break, {out} out today.',
    live: 'Live · updated {hhmm}',
    tiles: { now: 'Do now across team', help: 'May need help', noOwner: 'No owner', truck: 'Next truck' },
    tileSubs: {
      now: '{n} due by {hhmm}', help: '{title}, no update {n} min',
      noOwner: '{name} is out today', noOwnerNone: 'Everyone is on shift',
      truck: '{n} orders at risk · in {rel}', truckOnTrack: 'On track',
    },
    board: 'Team board', needsYou: 'Needs you', needsYouEmpty: 'Nothing needs you right now.',
    needsYouNoOwner: '{title}. No owner. Due {hhmm}.',
    needsYouHelp: '{title}. No update for {n} min.',
    needsYouAsked: '{name} asked for help on {title}.',
    rightNow: { working: 'Working on: {title} · {n} min', available: 'Available', onBreak: 'On break', out: 'Out today' },
    mayNeedHelp: 'May need help', load: { light: 'Light', busy: 'Busy', full: 'Full' },
    mirror: 'Everyone on the team sees this same board.', personNote: 'This is what {name} sees.',
    reassignTitle: 'Who should do this?', findTeammate: 'Find a teammate', suggested: 'Suggested',
    clearFilter: 'Clear filter',
  },
  trucks: { title: 'Next trucks', atRisk: '{n} orders at risk', onTrack: 'On track' },
  myShift: { title: 'My shift', doneOf: '{done} of {total} done', ends: 'Shift ends {hhmm}' },
  updates: { title: 'Updates', forYou: 'For you', team: 'Your team', activity: 'Activity', markRead: 'Mark as read',
             empty: 'No updates. When something changes, it will show up here.', seeAll: 'See all updates' },
  lookup: { empty: 'Type an order number, a name, or a word like printer.' },
  shortcuts: 'J K move · Enter open · E mark done · Z undo · ? all shortcuts',
  demo: { pill: 'Prototype controls', viewingAs: 'Viewing as', priya: 'Priya (coordinator)', danielle: 'Danielle (manager)',
          clock: 'Now {hhmm}', jump: 'Jump 15 min', reset: 'Reset to 10:40', inject: 'Send a new urgent item',
          wireframe: 'Wireframe mode', resetAll: 'Reset demo' },
  drawer: {
    assignedTo: 'Assigned to', ordersWaiting: 'Orders waiting', unitsAffected: 'Units affected',
    truck: 'Truck', created: 'Created', itemId: 'Item ID',
    activityCreated: 'Created {hhmm} by {source}', activityStarted: 'Started by {name} at {hhmm}',
    message: 'Message {name}', messagingToast: 'Messaging is not part of this prototype.',
  },
  howModal: {
    title: 'How we sort your work',
    body: 'We look at four things. How soon it is due. How many orders are waiting on it. Whether customers will feel it. Whether it is about safety or the law.',
    now: 'means a truck, a person, or many orders are at risk. Safety always goes here.',
    next: 'matters today, and a clock is running.',
    later: 'is real work, but nobody is blocked yet.',
    footer: 'Inside each group, the most important thing is on top. You can always ask for help or hand something off.',
  },
  waitingPopover: {
    who: 'Who are you waiting on?', suggestions: ['Carrier', 'Maintenance', 'Customer service', 'Vendor'],
    checkBack: 'Check back at', in30: 'In 30 min', in1h: 'In 1 hour', atCutoff: 'At {hhmm}',
  },
  notMineReasons: ['Wrong area', "I don't have access", 'Duplicate', 'Other'],
  moveLaterOptions: { in1h: 'In 1 hour', afterLunch: 'After lunch (12:30)', pick: 'Pick a time' },
  settings: { label: 'Settings', tooltip: 'Not part of this prototype' },
  sourceLabels: {
    order: 'Order', system: 'System', comms: 'Message', carrier: 'Carrier', customer: 'Customer',
    inventory: 'Inventory', safety: 'Safety', compliance: 'Compliance', floor: 'Floor', fyi: 'Info',
  },
  handheld: { needYou: '{n} need you' },
  chips: { workingOnIt: 'Working on it' },
  shift: { line: '{name} · {h}h {m}m left', ended: '{name} · Shift ended' },
}

export function t(str: string, vars: Record<string, string | number> = {}): string {
  return str.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? `{${key}}`))
}
