export const copy = {
  appName: 'Relay',
  nav: { work: 'My work', team: 'Team', updates: 'Updates', lookup: 'Look up' },
  search: 'Search orders, people, tickets',
  greeting: { morning: 'Good morning, {name}.', afternoon: 'Good afternoon, {name}.' },
  status: {
    needYou: '{n} things need you now.', needYouOne: '1 thing needs you now.',
    nothingUrgent: 'Nothing urgent. {n} left before your shift ends.',
    progress: '{done} of {total} done today.',
  },
  hero: { now: 'Do this now', next: 'Do this next', later: 'Up next when you are ready',
          of: '{i} of {n}', whyFirst: 'Why first:', nextStep: 'Next step: {action}',
          working: 'Working on it · {n} min' },
  actions: { start: 'Start', done: 'Mark done', help: 'Ask for help', more: 'More',
             waiting: 'Waiting on someone', notMine: 'Not mine', handOff: 'Hand off to a teammate',
             later: 'Move to later', reassign: 'Reassign', assign: 'Assign', seeWork: 'See work',
             checkIn: 'Check in', showMore: 'Show {n} more', showLess: 'Show less', undo: 'Undo',
             gotIt: 'Got it', showMe: 'Show me', stay: 'Stay here' },
  tiers: {
    now:   { label: 'Do now',       helper: 'A truck, a person, or many orders are at risk.' },
    next:  { label: 'Up next',      helper: 'Matters today. A clock is running.' },
    later: { label: 'Later today',  helper: 'Real work. Nobody is blocked yet.' },
    fyi:   { label: 'For your info',helper: 'No action needed.' },
    done:  { label: 'Done today' },
    empty: 'Nothing here.',
    waitingGroup: 'Waiting on others ({n})', laterGroup: 'Moved to later ({n})',
  },
  time: { dueIn: 'Due in {n} min', due: 'Due {hhmm}', lateMin: 'Late by {n} min', lateHr: 'Late by {n} h',
          tomorrow: 'Tomorrow {hhmm}' },
  why: { title: 'Why this is ranked here', showScore: 'Show the score', howLink: 'How we sort your work' },
  toast: { done: 'Done. {done} of {total} done today.', restored: 'Restored.', paused: 'Paused {title}.',
           moved: 'Moved to {name}.', sentBack: 'Sent back to the team.', helpSent: 'Sent to Danielle. She will check in.',
           waiting: 'Waiting on {who}. Back at {hhmm}.', notInPrototype: 'This is not part of the prototype.' },
  help: { title: "What's stopping you?", options: ['I need information','Something is broken','I need another person','Other'],
          note: 'Add a note (optional)', send: 'Send to Danielle', chip: 'Help asked' },
  laterDisabled: 'Do now items cannot be moved. Ask for help instead.',
  allClear: { title: "You're all caught up.", body: 'Nothing needs you right now. New work will show up here, already sorted.',
              meta: '{n} done today.', team: 'Help your team', updates: 'See updates' },
  newUrgent: 'New and more urgent: {title}.',
  changedPlace: '1 item changed place.', showIt: 'Show it',
  team: {
    status: 'Day shift · Outbound · {on} working, {brk} on break, {out} out today.',
    live: 'Live · updated {hhmm}',
    tiles: { now: 'Do now across team', help: 'May need help', noOwner: 'No owner', truck: 'Next truck' },
    board: 'Team board', needsYou: 'Needs you', needsYouEmpty: 'Nothing needs you right now.',
    rightNow: { working: 'Working on: {title} · {n} min', available: 'Available', onBreak: 'On break', out: 'Out today' },
    mayNeedHelp: 'May need help', load: { light: 'Light', busy: 'Busy', full: 'Full' },
    mirror: 'Everyone on the team sees this same board.', personNote: 'This is what {name} sees.',
    reassignTitle: 'Who should do this?', findTeammate: 'Find a teammate', suggested: 'Suggested',
  },
  trucks: { title: 'Next trucks', atRisk: '{n} orders at risk', onTrack: 'On track' },
  updates: { title: 'Updates', forYou: 'For you', team: 'Your team', activity: 'Activity', markRead: 'Mark as read',
             empty: 'No updates. When something changes, it will show up here.', seeAll: 'See all updates' },
  lookup: { empty: 'Type an order number, a name, or a word like printer.' },
  shortcuts: 'J K move · Enter open · E mark done · Z undo · ? all shortcuts',
  demo: { pill: 'Prototype controls', viewingAs: 'Viewing as', priya: 'Priya (coordinator)', danielle: 'Danielle (manager)',
          clock: 'Now {hhmm}', jump: 'Jump 15 min', reset: 'Reset to 10:40', inject: 'Send a new urgent item',
          wireframe: 'Wireframe mode', resetAll: 'Reset demo' },
}

export function t(str: string, vars: Record<string, string | number> = {}): string {
  return str.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? `{${key}}`))
}
